export const projects = [
  { 
    id: "01", 
    slug: "nordic-waterside",
    title: "Nordic Waterside", 
    category: "Residential • Copenhagen, DK", 
    image: "/images/img-1.jpg", 
    aspectRatio: "aspect-[4/5]",
    location: "Copenhagen, Denmark",
    year: "2024",
    client: "Efjord Developments",
    area: "450 sqm",
    description: "A minimalist residence situated on the edge of the Copenhagen harbor, Nordic Waterside explores the intersection of raw concrete and warm oak. The design emphasizes framed views of the water while maintaining a sense of sanctuary from the urban environment.",
    content: "The project was conceived as a series of interlocking volumes that respond to the coastal light. Large-format glazing allows for a seamless transition between the interior living spaces and the surrounding landscape, while the interior palette remains restrained to allow the natural surroundings to take center stage."
  },
  { 
    id: "02", 
    slug: "the-obsidian-pavillion",
    title: "The Obsidian Pavillion", 
    category: "Cultural • Tokyo, JP", 
    image: "/images/img-2.jpg", 
    aspectRatio: "aspect-square",
    location: "Tokyo, Japan",
    year: "2023",
    client: "Art Foundation Tokyo",
    area: "1,200 sqm",
    description: "A temporary exhibition space that challenges the traditional museum experience through a monochromatic palette and sharp, geometric forms.",
    content: "Inspired by volcanic glass, the Obsidian Pavillion features a faceted exterior that reflects the bustling city life of Tokyo in a distorted, abstract manner. Inside, the space is a void of light and shadow, designed to heighten the visitor's sensory perception of the exhibited artworks."
  },
  { 
    id: "03", 
    slug: "lumina-research-hub",
    title: "Lumina Research Hub", 
    category: "Institutional • Berlin, DE", 
    image: "/images/img-3.jpg", 
    aspectRatio: "aspect-[4/5]",
    location: "Berlin, Germany",
    year: "2024",
    client: "Lumina Science Institute",
    area: "4,500 sqm",
    description: "A state-of-the-art research facility designed to foster collaboration and transparency in the scientific community.",
    content: "The hub is organized around a central atrium that serves as a social heart, connecting various laboratories and office spaces. The use of translucent materials and adaptive lighting systems ensures that the building remains a beacon of light during the long Berlin winters."
  },
  { 
    id: "04", 
    slug: "ethereal-heights",
    title: "Ethereal Heights", 
    category: "Luxury Residential • Dubai, UAE", 
    image: "/images/img-4.jpg", 
    aspectRatio: "aspect-[3/4]",
    location: "Dubai, UAE",
    year: "2025",
    client: "Skyline Properties",
    area: "800 sqm",
    description: "A high-altitude penthouse that redefines luxury through vertical gardens and panoramic views of the Arabian Gulf.",
    content: "Ethereal Heights combines traditional Middle Eastern architectural elements with futuristic technology. The living spaces are designed to be fluid, with automated shading systems that respond to the sun's position, ensuring optimal comfort in the desert climate."
  },
  { 
    id: "05", 
    slug: "verdant-spire",
    title: "Verdant Spire", 
    category: "Commercial • Singapore, SG", 
    image: "/images/img-5.jpg", 
    aspectRatio: "aspect-[4/5]",
    location: "Singapore",
    year: "2023",
    client: "Green Horizon Group",
    area: "12,000 sqm",
    description: "A biophilic office tower that integrates over 50 species of tropical plants into its facade and interior social spaces.",
    content: "As a pioneer in sustainable commercial design, Verdant Spire features a natural ventilation system and greywater recycling. The building serves as a living laboratory for urban ecology, proving that high-density development can coexist with nature."
  },
  { 
    id: "06", 
    slug: "the-monolith-museum",
    title: "The Monolith Museum", 
    category: "Cultural • Oslo, NO", 
    image: "/images/img-6.jpg", 
    aspectRatio: "aspect-square",
    location: "Oslo, Norway",
    year: "2024",
    client: "Nordic Heritage Fund",
    area: "3,200 sqm",
    description: "A museum dedicated to contemporary sculpture, carved directly into the granite landscape of the Oslo fjord.",
    content: "The architecture is an exercise in subtraction, where spaces are excavated rather than built. The resulting atmosphere is one of profound stillness, where the weight of the stone contrasts with the delicate nature of the sculptures."
  },
  { 
    id: "07", 
    slug: "solaris-eco-village",
    title: "Solaris Eco-Village", 
    category: "Sustainable • Seville, ES", 
    image: "/images/img-7.jpg", 
    aspectRatio: "aspect-[4/5]",
    location: "Seville, Spain",
    year: "2024",
    client: "Solaris Living",
    area: "25,000 sqm",
    description: "A carbon-neutral residential community that utilizes passive cooling and large-scale solar integration to combat the Andalusian heat.",
    content: "The village is designed around the principles of the traditional Mediterranean courtyard house, optimized for modern living. Shared amenities include community gardens, an electric vehicle hub, and a central water feature that cools the entire complex through evaporation."
  },
  { 
    id: "08", 
    slug: "azure-coast-resort",
    title: "Azure Coast Resort", 
    category: "Hospitality • Mykonos, GR", 
    image: "/images/img-8.jpg", 
    aspectRatio: "aspect-[3/4]",
    location: "Mykonos, Greece",
    year: "2023",
    client: "Azure Luxury Hotels",
    area: "5,500 sqm",
    description: "A luxury resort that harmonizes with the Cycladic vernacular while introducing modern, expansive glass elements.",
    content: "Azure Coast is a celebration of the Aegean landscape. Each suite is carved into the hillside, offering private terraces and pools that overlook the horizon. The materials are locally sourced stone and whitewashed plaster, creating a timeless aesthetic."
  },
  { 
    id: "09", 
    slug: "zenith-workspace",
    title: "Zenith Workspace", 
    category: "Office • New York, USA", 
    image: "/images/img-9.jpg", 
    aspectRatio: "aspect-square",
    location: "New York, USA",
    year: "2024",
    client: "Zenith Tech",
    area: "2,500 sqm",
    description: "A flexible, post-pandemic office environment in the heart of Chelsea that prioritizes acoustic comfort and air quality.",
    content: "Zenith Workspace uses a modular design language that allows the space to evolve with the needs of its inhabitants. Sound-absorbing textures and an abundance of natural light create a calm, focused environment for the city's top tech talent."
  },
];

export const posts = [
  {
    slug: "evolution-of-minimalist-form",
    image: "/images/blog-1.jpg",
    date: "May 10, 2026",
    category: "Architecture",
    title: "The Evolution of Minimalist Form",
    desc: "How the purity of line and volume is being redefined in the era of digital fabrication and high-performance glass.",
    content: "Minimalism in architecture has long been associated with the 'less is more' philosophy of Mies van der Rohe. However, as we move deeper into the 21st century, a new form of minimalism is emerging—one that is driven not just by aesthetics, but by technological necessity and performance. \n\nToday, digital fabrication allows us to achieve tolerances that were previously impossible, while high-performance glass technology enables us to create expansive envelopes that disappear into the landscape. This article explores how these tools are being used to push the boundaries of what we consider 'minimal' in the built environment."
  },
  {
    slug: "carbon-neutral-craftsmanship",
    image: "/images/blog-2.jpg",
    date: "May 12, 2026",
    category: "Sustainability",
    title: "Carbon-Neutral Craftsmanship",
    desc: "A deep dive into cross-laminated timber and the renaissance of organic building materials in high-rise design.",
    content: "The construction industry is one of the largest contributors to global carbon emissions. In response, a new generation of architects is looking to the past to find the materials of the future. Cross-laminated timber (CLT) is at the center of this movement, offering a renewable, carbon-sequestering alternative to steel and concrete. \n\nFrom the wooden skyscrapers of Scandinavia to the boutique residential blocks of North America, we examine how CLT is changing the way we build and the way we think about the life cycle of our structures."
  },
  {
    slug: "15-minute-city-redux",
    image: "/images/blog-3.jpg",
    date: "May 15, 2026",
    category: "Urbanism",
    title: "The 15-Minute City Redux",
    desc: "Reimagining urban density to prioritize human interaction, walkable commerce, and accessible green infrastructure.",
    content: "The concept of the 15-minute city—where all essential needs are within a short walk or bike ride—has gained immense popularity in recent years. But as cities become more dense, how do we ensure that this model remains inclusive and vibrant? \n\nWe look at successful implementations in Paris, Bogota, and Barcelona, and discuss how architectural interventions can create the social 'glue' needed to make hyper-local living a reality for all citizens."
  },
  {
    slug: "biophilic-interiors",
    image: "/images/blog-4.jpg",
    date: "May 18, 2026",
    category: "Design",
    title: "Biophilic Interiors & Health",
    desc: "Integrating natural light, living walls, and fractals to enhance cognitive performance and emotional well-being.",
    content: "Humans have an innate connection to nature, yet we spend over 90% of our time indoors. Biophilic design seeks to bridge this gap by bringing the outside in. This isn't just about adding a few plants; it's about a fundamental shift in how we design our interior environments. \n\nResearch has shown that biophilic elements can reduce stress, improve recovery times in hospitals, and increase productivity in offices. We explore the latest trends in living walls, rhythmic lighting, and the use of natural fractals in interior finishes."
  },
  {
    slug: "ai-generative-architecture",
    image: "/images/blog-5.jpg",
    date: "May 20, 2026",
    category: "Technology",
    title: "AI in Generative Architecture",
    desc: "Exploring the symbiotic relationship between human intuition and machine-learned optimization in structural design.",
    content: "Artificial Intelligence is no longer a distant possibility in architecture; it is already here. Generative design algorithms can now process thousands of design permutations in seconds, optimizing for solar gain, structural efficiency, and material cost. \n\nBut where does this leave the architect? Rather than replacing human creativity, AI is acting as a powerful co-pilot, allowing us to explore more complex forms and solve more difficult problems. We profile several firms that are successfully integrating AI into their daily workflows."
  },
  {
    slug: "psychology-of-thresholds",
    image: "/images/blog-6.jpg",
    date: "May 25, 2026",
    category: "Theory",
    title: "The Psychology of Thresholds",
    desc: "Analyzing the transition between public and private spaces and its impact on the inhabitant's sense of security.",
    content: "The threshold is one of the most powerful elements in architecture. It is the moment of transition—the boundary between the chaos of the city and the sanctuary of the home. \n\nIn this theoretical exploration, we look at how different cultures have designed these transition zones, from the Japanese 'genkan' to the Roman 'vestibulum'. We also discuss how modern architecture often neglects these moments of pause and what we lose when the boundary between public and private becomes too thin."
  },
];
